# no installation...

# 1.9.1 is OK, since it is the most adopted version
install: "sudo apt-get build-dep ruby1.9.1"
before_script: autoconf
script: "./configure && make all test"

branches:
  only:
    - trunk
    - ruby_1_9_3
